### PR TITLE
minor adjustments

### PR DESCRIPTION
**Pull request by katyhuff**
Hi @ttimbers : your syllabus looks great! There were just a couple of typos. My only remaining comments are thus:

I am very interested in how the group code review sessions go. It might also be fund to combine this with pair programming or having students write unity tests together to support one another's work. On that topic, you mention a strict code of conduct, but say just to be a nice person. I would recommend linking to a code of conduct along the lines of what you mean by that -- students may benefit both from the clarity of explicitness and from the exposure to a proper code of conduct.

### CODE REVIEW

**Comment by katyhuff** [comment]
Whoops... there's something malformed about this pull request..  maybe because of the line-endings...

**Comment by katyhuff** [comment]
reopened... github seems to be choking on something in the rendering, but you can see all the changes in the rich diff: https://github.com/ttimbers/PHY3009/pull/2/files?short_path=906458c#diff-906458c0f57c7f5e5bb541844b060f86

**Comment by ttimbers** [comment]
Thanks @katyhuff ! I incorporated the changes highlighted in your rich diff, and I argee, it is probably best to be specific about the code of conduct. I have now linked to Software Carpentry's. Do you think it would be best to do the pair programming  and/or writing unit tests for each other during the code review, or perhaps maybe get them to do this during the work-along sessions when they are working in class on their final projects?

**Comment by katyhuff** [comment]
I'm surprised you couldn't just pull this pr? Is this pr closed, then?

Anyway, yeah, I think it would be fun to do pair programming in either or both of those stages of the process!! I've found that incorporating a little pair programming anywhere is good!

**Comment by ttimbers** [comment]
I was able to merge, it. Thanks again for your feedback!

**Comment by katyhuff** [comment]
Great!

**Pull request merged**
